college_erp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student.urls')),
    #path('',include('course.urls')),
    path('',include('coursemanagement.urls')),
    path('',include('feeplan.urls')),
    path('',include('employee.urls')),
    path('',include('user.urls')),
    path('',include('academics.urls')),  
    path('',include('exam.urls')),
    path('',include('collegesetup.urls')),
    path('',include('library.urls')),
    path('',include('hostel.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

exam/urls.py
from django.urls import path
from . import views


urlpatterns=[
    path('examtype_create/',views.ExamTypeCreate.as_view(), name='exam_type_create'),
    path('examtype_list/',views.exam_list_view, name='exam_type_list'),
    path('examtype_detail/<int:pk>/',views.ExamTypeDetailView.as_view(), name='examtype_detail'),
    path('examtype_update/<int:pk>/',views.ExamTypeUpdateView.as_view(), name='examtype_update'),
    path('examtype_delete/<int:pk>/',views.ExamTypeDeleteView.as_view(), name='examtype_delete'),
    path('course_exam_setting/',views.course_exam_setting, name='course_exam_setting'),
    path('course_exam_setting_ajax/',views.course_exam_setting_ajax, name='course_exam_setting_ajax'),
    path('save_course_exam/',views.save_course_exam, name='save_course_exam'),
    path('subjectexamlist/',views.subjectexamlist, name='subjectexamlist'),
    path('subject_exam_create/',views.SubjectExamCreate.as_view(), name='subject_exam_create'),
    path('subject_exam_update/<int:pk>/',views.SubjectExamPlanUpdate.as_view(), name='subject_exam_update'),
    path('subject_exam_delete/<int:pk>/',views.SubjectExamPlanDelete.as_view(), name='subject_exam_delete'),
    path('exam_attendance/',views.ExamAttendanceCreate.as_view(), name='exam_attendance'),
    path('load_subject_exam/',views.load_subject_exam, name='load_subject_exam'),
    path('examattendancecreate/',views.examattendancecreate, name='examattendancecreate'),
    path('save_exam_attendance/',views.save_exam_attendance, name='save_exam_attendance'),
    path('mark_entry/',views.mark_entry, name='mark_entry'), 
    path('load_date_on_subject_load/',views.load_date_on_subject_load, name='load_date_on_subject_load'),
    path('save_mark_entry/',views.save_mark_entry, name='save_mark_entry'),
    path('mark_entry_ajax/',views.mark_entry_ajax, name='mark_entry_ajax'),    
]

exam/models.py
from django.db import models
from academics.models import Semestar, Subject
from student.models import Student, Enrollment
from coursemanagement.models import Stream, Batch, Course

Attendance_Choice = (
    ('Absent', 'A'),
    ('Present', 'P'),
)

class ExamType(models.Model):
    exam_type = models.CharField(max_length=250)

    def __str__(self):
        return self.exam_type
    
class ExamSetting(models.Model):
    semestar = models.ForeignKey(Semestar, on_delete=models.CASCADE)
    exam = models.ForeignKey(ExamType, on_delete=models.CASCADE)
    no_of_exams = models.IntegerField()

    def __str__(self):
        return self.exam.exam_type

class SubjectExam(models.Model):
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE)
    exam = models.ForeignKey(ExamSetting,on_delete=models.CASCADE)
    full_mark = models.DecimalField(max_digits=5, decimal_places=2)
    total_student = models.IntegerField(default=0)
    exam_number = models.IntegerField(default=0)
    
    def __str__(self):
        return "{}-{}".format(self.exam.exam.exam_type,self.exam_number)


class ExamAttendance(models.Model):
    exam = models.ForeignKey(SubjectExam,on_delete=models.CASCADE)
    attendance_status = models.CharField(max_length=30,choices=Attendance_Choice)
    enrollment_number = models.ForeignKey(Enrollment, on_delete=models.CASCADE)
    date = models.DateField(auto_now=False,null=True,blank=True)
    marks = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    remarks = models.CharField(max_length=250, null=True, blank=True)

exam/forms.py
from django import forms
from .models import ExamSetting, ExamType, ExamAttendance, SubjectExam
from coursemanagement.models import Stream, Course, Batch
from academics.models import Semestar, Subject

class ExamTypeForm(forms.Form):
    exam_type = forms.CharField(max_length=250)   
          
    def save(self):
        data = self.cleaned_data
        user = ExamType(exam_type=data['exam_type'])
        user.save()

class CourseExamSetting(forms.ModelForm):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])
    semestar = forms.ChoiceField(choices=[(o.id, str(o)) for o in Semestar.objects.all()])
    
    class Meta:
        model = ExamSetting
        fields = ['exam','no_of_exams']

class SubjectExamForm(forms.ModelForm):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])
    semestar = forms.ChoiceField(choices=[(o.id, str(o)) for o in Semestar.objects.all()])   
    
    class Meta:
        model = SubjectExam
        fields = ['subject','exam','full_mark','exam_number']

class ExamAttendanceForm(forms.ModelForm):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])
    semestar = forms.ChoiceField(choices=[(o.id, str(o)) for o in Semestar.objects.all()])
    subject = forms.ChoiceField(choices=[(o.id, str(o)) for o in Subject.objects.all()])
    
    class Meta:
        model = ExamAttendance
        fields = ['attendance_status','exam','enrollment_number','date','marks','remarks']
        
class MarkentryForm(forms.Form):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])
    semestar = forms.ChoiceField(choices=[(o.id, str(o)) for o in Semestar.objects.all()])
    subject = forms.ChoiceField(choices=[(o.id, str(o)) for o in Subject.objects.all()])
    date = forms.ChoiceField(choices=[(o.date, str(o.date)) for o in ExamAttendance.objects.all()])
    exam = forms.ChoiceField(choices=[(o.id, str(o)) for o in SubjectExam.objects.all()])
    def save(self):
        data = self.cleaned_data
        user = ExamAttendance(marks=data['marks'])
        user.save()

exam/views.py
from django.shortcuts import render,redirect ,get_object_or_404
from django.urls import reverse_lazy
from .forms import ExamTypeForm, CourseExamSetting , SubjectExamForm, ExamAttendanceForm, MarkentryForm
from django.views.generic import ListView, UpdateView, DeleteView, DetailView, CreateView
from .models import ExamType, ExamSetting, SubjectExam, ExamAttendance
from django.http import HttpResponse
import json
from academics.models import Semestar, Subject
from student.models import Enrollment
from decimal import Decimal
from django.db.models import Count
from datetime import datetime
from django.utils.dateformat import DateFormat
from django.utils.formats import get_format
#from dateutil import parser

class DecimalEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, Decimal):
            return float(obj)
        return json.JSONEncoder.default(self, obj)

def load_subject_exam(request):
    subject_id = int(request.GET.get('subject_id'))
    subject = Subject.objects.get(pk=subject_id)
    subject_obj = SubjectExam.objects.filter(subject=subject.pk)
    return render(request,'exam/subject_exam_load_ajax.html',{'subject_obj':subject_obj})

from django.db import connection
def load_date_on_subject_load(request):
    exam_id = request.GET.get('exam_id')
   
    query = 'select distinct(date) from exam_examattendance where exam_examattendance.exam_id={0}'.format(exam_id)
    cursor = connection.cursor()
    print(query)
    cursor.execute(query)
    query_list = cursor.fetchall()
    exam_date_list = []
    for obj in query_list:
        exam_date_dict = {}
        exam_date_dict['date'] = obj[0]
        exam_date_list.append(exam_date_dict)
    return render(request,'exam/load_exam_on_subject_load_ajax.html',{'exam_date_list':exam_date_list}) 

class ExamTypeCreate(CreateView):
    model = ExamType
    form_class = ExamTypeForm
    template_name = 'exam/examtype_create_form.html'

    def get_context_data(self,**kwargs):
        context=super(ExamTypeCreate,self).get_context_data(**kwargs)
        return context
    
    
    def get(self,request,*args,**kwargs):        
        context={'form':ExamTypeForm()}
        return render(request,'exam/examtype_create_form.html',context)
        
    
    def post(self,request,*args,**kwargs):        
        form=ExamTypeForm(request.POST or None,request.FILES or None)
        if form.is_valid():
            form.save()
            return redirect('exam_type_list')
        return render(request,'exam/examtype_create_form.html',{'form':form})

def exam_list_view(request):
    queryset=ExamType.objects.all().order_by('-id')
    context = {
        'queryset':queryset,
    }
    return render(request, 'exam/examtype_list.html', context)

class ExamTypeDetailView(DetailView):
    context_object_name='examtype_detail'
    template_name='exam/examtype_detail.html'
    queryset=ExamType.objects.all()
    
    def get_context_data(self, *args ,**kwargs):
        context = super(ExamTypeDetailView, self).get_context_data(**kwargs)
        #context['username'] = self.request.session['username']     
        return context
    
class ExamTypeUpdateView(UpdateView):
    model = ExamType
    template_name='exam/examtype_update_form.html'
    success_url=reverse_lazy('exam_type_list')
    form_class = ExamTypeForm

    def post(self, request, pk, *args, **kwargs):
        instance = get_object_or_404(ExamType, pk=pk)
        form = ExamTypeForm(request.POST or None, request.FILES or None, instance=instance)
        print(pk)
        if form.is_valid():
            form.save()
        return redirect(reverse_lazy('exam_type_list'))

class ExamTypeDeleteView(DeleteView):
    model = ExamType
    success_url=reverse_lazy('exam_type_list')

def course_exam_setting(request):
    if request.method == "POST":
        stream = request.POST.get('stream')
        course = request.POST.get('course')
        batch = request.POST.get('batch')
        semestar = request.POST.get('semestar')        
        exam_type = ExamType.objects.all()
        context = {
            'semestar':semestar,
            'exam_type':exam_type,
        }
    else:
        form = CourseExamSetting()
        context = {'form':form}
    return render(request,'exam/course_exam_setting.html',context)

def course_exam_setting_ajax(request):
    if request.method == "POST":
        stream = request.POST.get('stream')
        course = request.POST.get('course')
        batch = request.POST.get('batch')
        semestar = request.POST.get('semestar')        
        exam_type = ExamType.objects.all()
        exam_type_list=[]
        for i in exam_type:
            exam_type_dic={}
            exam_type_dic['exam_type'] = i.exam_type
            exam_type_dic['id'] = i.pk
            exam_type_list.append(exam_type_dic)
        context = {
            'semestar':semestar,
            'exam_type_list':exam_type_list,
        }
        course_exam = json.dumps(context)
        return HttpResponse(course_exam, 'application/json')
    else:
        form = CourseExamSetting()
        context = {'form':form}
    return render(request,'exam/course_exam_setting_ajax.html',context)

def save_course_exam(request):
    try:
        total_count = int(request.POST.get('total_count'))
        semestar = request.POST.get('semestar')  
        print(semestar)
        semestar_obj =Semestar.objects.get(pk=semestar)
        exam_type = request.POST.get('attn_list[1]')
        print(exam_type)
        for i in range(total_count):
            exam_type = request.POST.get('attn_list['+ str(i) +'][exam_type_id]')
            nums = request.POST.get('attn_list['+ str(i) +'][nums_id]')
            examsetting_obj = ExamSetting()
            examsetting_obj.semestar = semestar_obj
            examsetting_obj.exam = ExamType.objects.get(pk=exam_type)
            examsetting_obj.no_of_exams = nums
            print(examsetting_obj.semestar, examsetting_obj.exam, examsetting_obj.no_of_exams)
            examsetting_obj.save()
        exam_json = json.dumps({"msg":"success"})
        return HttpResponse(exam_json, 'application/json')

    except Exception as e:
        print(e)

class SubjectExamCreate(CreateView):
    model = SubjectExam
    form_class = SubjectExamForm
    template_name = 'exam/subject_exam_create.html'

    def get_context_data(self,**kwargs):
        context=super(SubjectExamCreate,self).get_context_data(**kwargs)
        return context
    def get(self,request,*args,**kwargs):        
        context={'form':SubjectExamForm()}
        return render(request,'exam/subject_exam_create.html',context)        
    
    def post(self,request,*args,**kwargs):        
        form=SubjectExamForm(request.POST or None,request.FILES or None)
        if form.is_valid():
            form.save()
            return redirect('subjectexamlist')
        return render(request,'exam/subject_exam_create.html',{'form':form})

def subjectexamlist(request):
    queryset = SubjectExam.objects.all()
    context = {
        'queryset':queryset,
    }
    return render(request,'exam/subject_exam_setting.html',context)
class SubjectExamPlanUpdate(UpdateView):
    model = SubjectExam
    form_class = SubjectExamForm
    template_name = 'exam/subject_exam_create.html'

    def get_context_data(self,**kwargs):
        context=super(SubjectExamPlanUpdate,self).get_context_data(**kwargs)
        return context
    def get(self,request,*args,**kwargs):        
        context={'form':SubjectExamForm()}
        return render(request,'exam/subject_exam_create.html',context)    
    
    def post(self, request, pk, *args, **kwargs):
        instance = get_object_or_404(SubjectExam, pk=pk)
        form = SubjectExamForm(request.POST or None, request.FILES or None, instance=instance)
        print(pk)
        if form.is_valid():
            form.save()
        return redirect(reverse_lazy('subjectexamlist'))

class SubjectExamPlanDelete(DeleteView):
    model = SubjectExam
    success_url=reverse_lazy('subjectexamlist')

def examattendancelist(request):
    queryset = ExamAttendance.objects.all()
    context = {
        'queryset':queryset,
    }
    return render(request,'exam/exam_attendance.html',context)


class ExamAttendanceCreate(CreateView):
    model = ExamAttendance
    form_class = ExamAttendanceForm
    template_name = 'exam/exam_attendance_create.html'

    def get_context_data(self,**kwargs):
        context=super(ExamAttendanceCreate,self).get_context_data(**kwargs)
        return context
    def get(self,request,*args,**kwargs):        
        context={'form':ExamAttendanceForm()}
        return render(request,'exam/exam_attendance_create.html',context)        
    
    def post(self,request,*args,**kwargs):        
        form=ExamAttendanceForm(request.POST or None,request.FILES or None)
        if form.is_valid():
            form.save()
            return redirect('subjectexamlist')
        return render(request,'exam/exam_attendance_create.html',{'form':form})

def examattendancecreate(request):
    stream = request.POST.get('stream_id')
    course = request.POST.get('course')        
    batch = request.POST.get('batch_id')        
    semestar = request.POST.get('semestar_id')        
    subject = request.POST.get('subject_id')       
    exam = request.POST.get('exam_id')
    print(exam)
    sub_obj = SubjectExam.objects.get(pk=exam)
    enr_obj = Enrollment.objects.filter(batch=batch)
    exam_obj_dic = {}
    exam_obj_dic['id'] = sub_obj.id
    exam_obj_dic['subject'] =sub_obj.subject.name
    exam_obj_dic['exam'] = sub_obj.exam.exam.exam_type
    exam_obj_dic['full_mark'] = sub_obj.full_mark
    exam_obj_dic['exam_number'] = sub_obj.exam_number
    
    enr_obj_list =[]
    for i in enr_obj:
        enr_obj_dic = {}
        enr_obj_dic['id'] = i.id
        enr_obj_dic['enrollment_number'] = i.enrollment_number
        enr_obj_dic['student_name'] = i.student_name.first_name+" "+i.student_name.last_name

exam/templates/exam/course_exam_setting_ajax.html
<table class="table table-bordered table-striped table-condensed" id="table_id">
    <thead>
        <tr class="hdclr">
            <th>Sl No</th>
            <th>Exam</th>
            <th>No of Exams</th>  
        </tr>
    </thead>
    <tbody id="course_exam">   

            {% for stud in exam_type_list %}     
        <tr>                                                           
            <td>{{stud.id}}</td> 
            <td><input type="hidden" name="student_section_assign" id="stud_exam_type" hidden="hidden">{{stud.exam_type}}</td>              
            <td>
                <input type="hidden" name="student_section_assign" id="exam_type" hidden="hidden">
                <input type="text" name="course-exam_setting" id="course_exam">
                
            </td>
        </tr>  
        {% endfor %}       
    </tbody>
</table>

<script>


function getCookie(c_name) {
    if (document.cookie.length > 0)
    {
        c_start = document.cookie.indexOf(c_name + "=");
        if (c_start != -1)
        {
            c_start = c_start + c_name.length + 1;
            c_end = document.cookie.indexOf(";", c_start);
            if (c_end == -1) c_end = document.cookie.length;
            return unescape(document.cookie.substring(c_start,c_end));
        }
    }
    return "";
}
$(function(){
    $.ajaxSetup({
        headers:{"X-CSRFToken":getCookie('csrftoken')}
    });
});
</script>

exam/templates/exam/examtype_confirm_delete.html
<section>     
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input type="submit" value="Submit" class="btmnhk"  />
    </form>
</section>

exam/templates/exam/examtype_detail.html
{{object.exam_type}}

exam/templates/exam/load_exam_on_subject_load_ajax.html
<option value="0">-----------------------</option>
{% for i in exam_date_list %}
<option value="{{i.date}}">{{i.date}}</option>
{% endfor %}

exam/templates/exam/mark_entry.html
{% extends 'student/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<section id="main-content">
    <div class="wrapper">
        <div class="col-sm-12 col-xs-12 col-sm-offset-0">
            <div class="text-center">
                <h1 class="hdrcolorbg">
                    Exam Mark Entry Form
                </h1>
            </div>
            <form class="frmbgg clear-fx"  method="post"  id="assignSubjectTeacherForm" data-course-url="{% url 'ajax_load_course' %}" data-batch-url="{% url 'ajax_load_batch' %}" data-semestar-url="{% url 'ajax_load_sem' %}"  data-subject-url="{% url 'ajax_load_subject' %}">
                <div class="row">
                    {% csrf_token %}
                    <div class="form-group col-sm-3 col-xs-12">
                        <label>Stream</label>
                        {{ form.stream}}
                    </div>
                    <div class="form-group col-sm-3 col-xs-12">
                        <label>Course</label>
                        {{ form.course}}
                    </div>
                    <div class="form-group col-sm-3 col-xs-12">
                        <label>Batch</label>
                        {{ form.batch}}
                    </div>
                    <div class="form-group col-sm-3 col-xs-12">
                        <label>Semestar</label>
                        {{ form.semestar}}
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-3 col-xs-12">
                        <label>Subject</label>
                        {{ form.subject}}
                    </div>                        
                    <div class="form-group col-sm-3 col-xs-12">
                        <label>Exam</label>                        
                        {{ form.exam}}
                    </div>  
                    <div class="form-group col-sm-3 col-xs-12">
                        <label>Date</label>
                        {{ form.date}}
                    </div>
            </form>
        </div>        
    </div>  
    <div class="col-sm-12 col-xs-12">
        <table class="table table-bordered table-striped table-condensed" id="">
            <thead>
                <tr class="hdclr">
                    <th>Sl No</th>
                    <th>Enrollment Number</th>
                    <!-- <th>Name</th> -->
                    <th>Attendance</th>
                    <th>Mark</th>
                    <th>ReMark</th>                
                </tr>
            </thead>
            <tbody id="marks_entry">   
                
            </tbody>
        </table>
            <button class="btn btn-info save" id="submit_attn">Submit</button>
            <input type="hidden" name="student_section" id="total_count" hidden="hidden" value="">
    </div>
</section>
<script type="text/javascript">
    $("#id_stream").change(function(){
        var url=$("#assignSubjectTeacherForm").attr("data-course-url");
        var stream_id=$(this).val();
        $.ajax({
            url:url,
        data:{
            'stream':stream_id,
        },
        success:function(data){
            $("#id_course").html(data);
        }
        });
    });
    $("#id_course").change(function(){
        var url=$("#assignSubjectTeacherForm").attr("data-batch-url");
        var course_id=$(this).val();
        $.ajax({
            url:url,
            data:{
                'course':course_id,
            },
            success:function(data){
                $("#id_batch").html(data);
            }
        });
    });
    $("#id_batch").change(function(){
        var url=$("#assignSubjectTeacherForm").attr("data-semestar-url");
        var batch_id=$(this).val();
        var course_id=$("#id_course").val();
        var stream_id = $("#id_stream").val();
        $.ajax({
            url:url,
            data:{
                'batch_id': batch_id,
                'course':course_id,
                'stream_id': stream_id,
            },
            success:function(data){
                $("#id_semestar").html(data);
            }
        });
    });
    $("#id_semestar").change(function(){
        var url=$("#assignSubjectTeacherForm").attr("data-subject-url");
        var semestar_id = $(this).val();
        var batch_id=$("#id_batch").val();
        var course_id=$("#id_course").val();
        var stream_id = $("#id_stream").val();
        $.ajax({
            url:url,
            data:{
                'semestar_id':semestar_id,
                'batch_id': batch_id,
                'course':course_id,
                'stream_id': stream_id,
            },
            success:function(data){
                $("#id_subject").html(data);
            }
        });
    });
    $("#id_subject").change(function(){
        var subject_id = $(this).val();
        var semestar_id = $("#id_semestar").val();
        var batch_id=$("#id_batch").val();
        var course_id=$("#id_course").val();
        var stream_id = $("#id_stream").val();
        $.ajax({
            url:'/load_subject_exam/',
            data:{
                'semestar_id':semestar_id,
                'batch_id': batch_id,
                'course':course_id,
                'stream_id': stream_id,
                'subject_id':subject_id,
            },
            success:function(data){
                $("#id_exam").html(data);
            }
        });
    });
    $("#id_exam").change(function(){
        console.log("exam loads here");
        var exam_id = $("#id_exam").val();
        var semestar_id = $("#id_semestar").val();
        var batch_id=$("#id_batch").val();
        var course_id=$("#id_course").val();
        var stream_id = $("#id_stream").val();
        var subject_id = $("#id_subject").val();
        $.ajax({
            url:'/load_date_on_subject_load/',
            data:{
                'semestar_id':semestar_id,
                'batch_id': batch_id,
                'course':course_id,
                'stream_id': stream_id,
                'subject_id':subject_id,
                'exam_id':exam_id,
            },
            success:function(data){
                $("#id_date").html(data);
                console.log("data comes here");
            }
        });
    });
    $("#id_date").change(function(){
        console.log("mark entry starts here");        
        var date_id = $(this).val();
        var exam_id = $("#id_exam").val();
        var subject_id = $("#id_subject").val();
        var semestar_id = $("#id_semestar").val();
        var batch_id=$("#id_batch").val();
        var course_id=$("#id_course").val();
        var stream_id = $("#id_stream").val();
        let date_sending = new Date(date_id);
        let formatted_date = date_sending.getFullYear()+"-"+(date_sending.getMonth()+1)+"-"+date_sending.getDate();
        console.log(formatted_date);
        $.ajax({
            url:"/mark_entry_ajax/",
            type:'POST',
            data:{
                'semestar_id':semestar_id,
                'batch_id': batch_id,
                'course':course_id,
                'stream_id': stream_id,
                'subject_id':subject_id,
                'exam_id':exam_id, 
                'date_id':date_id,         
            },
            success:function(data){              
                $("#marks_entry").val(data.mark_obj_list);
                var tableString = "";
                if(data.mark_obj_list.length === 0) {
                    tableString = "<tr><td></td><td>No Data Available.</td><td></td></tr>";
                }
                else {
                    for(var i=1;i<= data.mark_obj_list.length;i++){
                        tableString += "<tr><td>"+ i +"</td><td>" + data.mark_obj_list[i-1].enrollment_number + "</td>";                                      
                        tableString += "<input type=\"hidden\" id=\"exam_attendance_name"+i+"\" value=\""+data.mark_obj_list[i-1].id+"\">" + data.mark_obj_list[i-1].enrollment_number + "</td>";    
                        // tableString += "<td>"+data.mark_obj_list[i-1].enrollment_number.student_name.first_name + "</td>";   
                        tableString += "<td><select name=\"attendance\" id=\"nums"+i+"\">";                        
                        tableString += "<option value=\"P\">P</option><option value=\"A\">A</option><option value=\"L\">L</option></select></td>";
                        tableString += "<td><input type=\"text\" id=\"attendance_marks"+i+"\"  placeholder=\" Enter marks\"></td>";
                        tableString += "<td><input type=\"text\" id=\"attendance_remarks"+i+"\"  placeholder=\" Enter remarks\"></td>";
                        tableString += "</tr>";
                        // var nums =  "#nums"+i;
                        // var nums_id = $(nums).val();
                        // var attendance_marks = "#attendance_marks"+i;         
                        // var attendance_marks_id = $(attendance_marks).val();
                        
                    }                                          
                }
                
                console.log(tableString);
                $("#marks_entry").html(tableString);
                $("#total_count").val(data.mark_obj_list.length);
            }
        });
  });
    
    $("#submit_attn").on('click', function(){
        console.log("coming here to save part");
        var semestar = $('#id_semestar').val();
        var subject = $('#id_subject').val();
        var exam = $('#id_exam').val();
        var total_count = $('#total_count').val();
        var date = $('#date').val();
        if(total_count>0)
        {
            var attn_list = new Array();
            for(i=1;i<=total_count;i++){
                var exam_attendance = "#exam_attendance_name"+i;
                var exam_attendance_id = $(exam_attendance).val();
                var nums = "#nums"+i;
                var nums_id = $(nums).val();
                var attendance_marks = "#attendance_marks"+i;
                var attendance_marks_id = $(attendance_marks).val();
                var attendance_remarks = "#attendance_remarks"+i;
                var attendance_remarks_id = $(attendance_remarks).val();
                attn_list.push({ "exam_attendance_id":exam_attendance_id, "nums_id": nums_id,'attendance_marks_id':attendance_marks_id, 'attendance_remarks_id':attendance_remarks_id});
                console.log(attn_list);
            }
            $.ajax(
            { 
                method: "POST",
                url:"/save_mark_entry/",
                data:{
                    'attn_list':attn_list,
                    'total_count':total_count,
                    'semestar':semestar,
                    'subject':subject,
                    'exam':exam,                
                },
                success:function(data){
                    if(data.msg=="success"){
                        alert(data.msg);                   
                    } 
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) { 
                        alert("Status: " + textStatus); alert("Error: " + errorThrown); 
                    }
            });
        }        
    });    
    function getCookie(c_name) {
        if (document.cookie.length > 0)
        {
            c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1)
            {
                c_start = c_start + c_name.length + 1;
                c_end = document.cookie.indexOf(";", c_start);
                if (c_end == -1) c_end = document.cookie.length;
                return unescape(document.cookie.substring(c_start,c_end));
            }
        }
        return "";
    }
    $(function(){
        $.ajaxSetup({
            headers:{"X-CSRFToken":getCookie('csrftoken')}
        });
    });
</script>
{% endblock content %}

exam/templates/exam/subject_exam_load_ajax.html
<option value="0">---------------------------------------------</option>
{% for i in subject_obj %}
<option value="{{i.id}}">{{i}}</option>
{% endfor %}