college_erp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student.urls')),
    #path('',include('course.urls')),
    path('',include('coursemanagement.urls')),
    path('',include('feeplan.urls')),
    path('',include('employee.urls')),
    path('',include('user.urls')),
    path('',include('academics.urls')),  
    path('',include('exam.urls')),
    path('',include('collegesetup.urls')),
    path('',include('library.urls')),
    path('',include('hostel.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

exam/urls.py
from django.urls import path
from . import views


urlpatterns=[
    path('examtype_create/',views.ExamTypeCreate.as_view(), name='exam_type_create'),
    path('examtype_list/',views.exam_list_view, name='exam_type_list'),
    path('examtype_detail/<int:pk>/',views.ExamTypeDetailView.as_view(), name='examtype_detail'),
    path('examtype_update/<int:pk>/',views.ExamTypeUpdateView.as_view(), name='examtype_update'),
    path('examtype_delete/<int:pk>/',views.ExamTypeDeleteView.as_view(), name='examtype_delete'),
    path('course_exam_setting/',views.course_exam_setting, name='course_exam_setting'),
    path('course_exam_setting_ajax/',views.course_exam_setting_ajax, name='course_exam_setting_ajax'),
    path('save_course_exam/',views.save_course_exam, name='save_course_exam'),
    path('subjectexamlist/',views.subjectexamlist, name='subjectexamlist'),
    path('subject_exam_create/',views.SubjectExamCreate.as_view(), name='subject_exam_create'),
    path('subject_exam_update/<int:pk>/',views.SubjectExamPlanUpdate.as_view(), name='subject_exam_update'),
    path('subject_exam_delete/<int:pk>/',views.SubjectExamPlanDelete.as_view(), name='subject_exam_delete'),
    path('exam_attendance/',views.ExamAttendanceCreate.as_view(), name='exam_attendance'),
    path('load_subject_exam/',views.load_subject_exam, name='load_subject_exam'),
    path('examattendancecreate/',views.examattendancecreate, name='examattendancecreate'),
    path('save_exam_attendance/',views.save_exam_attendance, name='save_exam_attendance'),
    path('mark_entry/',views.mark_entry, name='mark_entry'), 
    path('load_date_on_subject_load/',views.load_date_on_subject_load, name='load_date_on_subject_load'),
    path('save_mark_entry/',views.save_mark_entry, name='save_mark_entry'),
    path('mark_entry_ajax/',views.mark_entry_ajax, name='mark_entry_ajax'),    
]

feeplan/urls.py
from django.urls import path
from . import views


urlpatterns=[
   
    path('feeplan_create/', views.FeesPlanTypeCreate.as_view(), name='feeplan_create'),
    path('feeplan_list/', views.FeesPlanTypeView.as_view(), name='feeplan_list'),
    path('ajax_load_list_data/', views.ajax_load_list_data, name="ajax_load_list_data"),
    #path('feecollection/', views.feecollection, name="feecollection"),
    path('plancollection/<int:id>/',views.FeePlanCreate.as_view(), name='plan_collection'),
    path('add_note/', views.add_note, name='note'),
    path('pin_toggle_note/', views.pin_toggle_note, name='pin_toggle_note'),
    path('approvecollection/<int:id>/',views.FeePlanApprove.as_view(), name='approve_collection'),
    path('fee/collect_fee/<int:id>/', views.CollectFee.as_view(), name="collect_fee"),
    path('feeplan/save_fee/', views.collectfeesave, name="save_fee"),
    path('get_remaning_fee_list/', views.get_remaning_fee_list, name="get_remaning_fee_list"),
    path('collect_student_fee/', views.collect_student_fee, name="collect_student_fee"),
    path('pay_by_id/', views.pay_by_id, name="pay_by_id"),
    path('viewfeedetails/<int:id>', views.viewfeedetails, name="viewfeedetails"),
    path('viewfeedetailsdetail/<int:id>', views.viewfeedetailsdetail, name="viewfeedetailsdetail"),
    path('printfee_pdf/<int:id>', views.printfee_pdf, name="printfee_pdf"),
    path('pay_multiple_fee/', views.pay_multiple_fee, name="pay_multiple_fee"),
    path('moneyreceiptdetails/', views.moneyreceiptdetails, name="moneyreceiptdetails"),
    path('ajax_load_list_data_fee/', views.ajax_load_list_data_fee, name="ajax_load_list_data_fee"),


    
]

feeplan/models.py
from django.db import models
from coursemanagement.models import FeesManagementSetting,Feestype,Course,Stream,Batch
from student.models import Student,Enrollment
from coursemanagement.models import Feestype
import datetime
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

class FeesPlanType(models.Model):
    stream=models.ForeignKey(Stream,on_delete=models.CASCADE)
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    batch=models.ForeignKey(Batch,on_delete=models.CASCADE)
    fees_type=models.ForeignKey(Feestype, on_delete=models.CASCADE)
    year = models.DateField(null=True, blank=True)
    actual_fees=models.DecimalField(max_digits=10,decimal_places=2,null=True, blank=True)
    default_installment=models.IntegerField(default=1,null=True, blank=True)

class ApproveFeeplanType(models.Model):
    student=models.ForeignKey(Student,on_delete=models.CASCADE, null=True, blank=True)
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    batch=models.ForeignKey(Batch,on_delete=models.CASCADE)
    fees_node=models.ForeignKey(FeesPlanType,on_delete=models.CASCADE)
    approve_fees = models.DecimalField(max_digits=10,decimal_places=2, null=True, blank=True)
    no_of_installments = models.IntegerField(blank=True, null=True)
    first_installment = models.DecimalField(max_digits=10,decimal_places=2, blank=True, null=True)
    due_date_first_installment = models.DateField(default=datetime.date.today, blank=True, null=True)
    second_installment = models.DecimalField(max_digits=10,decimal_places=2, blank=True, null=True)
    due_date_second_installment = models.DateField(default=datetime.date.today, blank=True, null=True)
    third_installment = models.DecimalField(max_digits=10,decimal_places=2, blank=True, null=True)
    due_date_third_installment = models.DateField(default=datetime.date.today, blank=True, null=True)

class Note(models.Model):
    note=models.TextField()
    student_admission_id=models.ForeignKey(Student, on_delete=models.SET_NULL, null = True, blank = True)
    user_id=models.ForeignKey(User, on_delete=models.CASCADE)
    note_type= models.IntegerField(default=1)
    is_pin=models.BooleanField(default=False)
    is_active=models.BooleanField(default=True)


class FeeCollect(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    approve_fee = models.ForeignKey(ApproveFeeplanType, on_delete=models.CASCADE)
    installment_number = models.IntegerField(default=1)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    amount_left = models.DecimalField(max_digits=10, default=0, decimal_places=2, null=True, blank=True)
    date= models.DateField(default=datetime.date.today)
    is_active = models.BooleanField(default=True)
    

class FeeDetails(models.Model):
    fee = models.ForeignKey(FeeCollect, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    pay_date = models.DateField(default=datetime.date.today)
    is_active = models.BooleanField(default=True)

class MoneyReceipt(models.Model):
    mr_no = models.CharField(max_length=250, null=True, blank=True)
    enrollment_number = models.ForeignKey(Enrollment, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

class MoneyReceiptDetails(models.Model):
    money_receipt = models.ForeignKey(MoneyReceipt, on_delete=models.CASCADE)
    fee_details = models.ForeignKey(FeeDetails, on_delete=models.CASCADE)

exam/forms.py
from django import forms
from .models import ExamSetting, ExamType, ExamAttendance, SubjectExam
from coursemanagement.models import Stream, Course, Batch
from academics.models import Semestar, Subject

class ExamTypeForm(forms.Form):
    exam_type = forms.CharField(max_length=250)   
          
    def save(self):
        data = self.cleaned_data
        user = ExamType(exam_type=data['exam_type'])
        user.save()

class CourseExamSetting(forms.ModelForm):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])
    semestar = forms.ChoiceField(choices=[(o.id, str(o)) for o in Semestar.objects.all()])
    
    class Meta:
        model = ExamSetting
        fields = ['exam','no_of_exams']

class SubjectExamForm(forms.ModelForm):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])
    semestar = forms.ChoiceField(choices=[(o.id, str(o)) for o in Semestar.objects.all()])   
    
    class Meta:
        model = SubjectExam
        fields = ['subject','exam','full_mark','exam_number']

class ExamAttendanceForm(forms.ModelForm):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])
    semestar = forms.ChoiceField(choices=[(o.id, str(o)) for o in Semestar.objects.all()])
    subject = forms.ChoiceField(choices=[(o.id, str(o)) for o in Subject.objects.all()])
    
    class Meta:
        model = ExamAttendance
        fields = ['attendance_status','exam','enrollment_number','date','marks','remarks']
        
class MarkentryForm(forms.Form):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])
    semestar = forms.ChoiceField(choices=[(o.id, str(o)) for o in Semestar.objects.all()])
    subject = forms.ChoiceField(choices=[(o.id, str(o)) for o in Subject.objects.all()])
    date = forms.ChoiceField(choices=[(o.date, str(o.date)) for o in ExamAttendance.objects.all()])
    exam = forms.ChoiceField(choices=[(o.id, str(o)) for o in SubjectExam.objects.all()])
    def save(self):
        data = self.cleaned_data
        user = ExamAttendance(marks=data['marks'])
        user.save()

feeplan/forms.py
from django import forms
from .models import FeesPlanType,ApproveFeeplanType



class FeesPlanTypeForm(forms.ModelForm):
    class Meta:
        model=FeesPlanType
        fields=('__all__')

class ApproveFeePlanTypeForm(forms.ModelForm):
    class Meta:
        model=ApproveFeeplanType
        fields=('student','course','batch','fees_node','approve_fees','no_of_installments','first_installment',\
            'due_date_first_installment','third_installment','due_date_third_installment',\
            'second_installment','due_date_second_installment')
        #exclude=('third_installment','due_date_third_installment')

feeplan/templates/feeplan/Untitled.html
{% extends 'student/base.html' %}
{% block content %}
<section id="main-content">
        <div class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel">
                        <header class="panel-heading clearfix col-sm-12">                            
                            <input type="text" id="enr_id" name="enr_number">
                            <button class="btn btn-info okbtn" id="enr_submit">View Fee</button>
                        </header>                     
                    </div>
                </div>    
            </div>           
        </div>
        <div class="container">
            <div class="panel panel-default">
                    <input type="text" id="stud_name" name="stud_name">
              <div class="panel-heading" data-toggle="collapse" data-target="#demo1">First Installment</div>
              <div class="panel-body collapse" id="demo1">
                  <table class="table">
                      <thead>
                            <td>Type</td>
                            <td>Amount</td>
                            <td>Paid</td>
                            <td>Left</td>
                            <td>Pay</td>
                            <td>Action</td>
                      </thead>
                      <tbody id="tbody1">
                    
                    </tbody>
                  </table>
              </div>
            </div>
        </div>
        <div class="container">
            <div class="panel panel-default">
              <div class="panel-heading" data-toggle="collapse" data-target="#demo2">Second Installment</div>
              <div class="panel-body collapse" id="demo2">
                    <table class="table">
                            <thead>
                                  <td>Type</td>
                                  <td>Amount</td>
                                  <td>Paid</td>
                                  <td>Left</td>
                                  <td>Pay</td>
                                  <td>Action</td>
                            </thead>
                            <tbody id="tbody2">
                          
                          </tbody>
                        </table>
              </div>
            </div>
        </div>
        <div class="container">
            <div class="panel panel-default">
              <div class="panel-heading" data-toggle="collapse" data-target="#demo3">Third Installment</div>
              <div class="panel-body collapse" id="demo3">
                    <table class="table">
                            <thead>
                                  <td>Type</td>
                                  <td>Amount</td>
                                  <td>Paid</td>
                                  <td>Left</td>
                                  <td>Pay</td>
                                  <td>Action</td>
                            </thead>
                            <tbody id="tbody3">
                          
                          </tbody>
                        </table>
              </div>
            </div>
        </div>
    </section>
    

<script type="text/javascript">
    $("#enr_submit").on('click', function(event){
        event.preventDefault();
        var enr_number=$("#enr_id").val();
    $.ajax({
        type:'GET',
        url:'/get_remaning_fee_list/',
        data:{
        'enr_number':enr_number,
        },
        success:function(data){
            $("#stud_name").val(data.student_name);
                var tableString = "";
                if(data.first_fee_list.length === 0) {
                    tableString = "<tr><td></td><td>No fee available.</td><td></td><td></td></tr>";
                }
                else {
                    for(var i in data.first_fee_list){
                        tableString += "<tr><td>" + data.first_fee_list[i].fee_type + "</td>";
                        tableString += "<td>" + data.first_fee_list[i].fee_amount + "</td>";
                        tableString += "<td>" + data.first_fee_list[i].fee_paid + "</td>";
                        tableString += "<td>" + data.first_fee_list[i].fee_left + "</td>";
                        if(data.first_fee_list[i].fee_left>0){
                            tableString += "<td><input type='text' id='amount"+data.first_fee_list[i].fee_id+"'></td>";
                            tableString += "<td><a type='button' class='btn btn-info savepay' onclick='pay_amount("+data.first_fee_list[i].fee_id+")'>Submit</a></td></tr>";
                        } else {
                            tableString += "<td></td>";
                            tableString += "<td></tr>";
                        }
                    }
                }
                $("#tbody1").html(tableString);
                tableString = "";
                if(data.second_fee_list.length === 0) {
                    tableString = "<tr><td></td><td></td><td>No fee available.</td><td></td><td></td></tr>";
                }
                else {
                    for(var i in data.second_fee_list){
                        tableString += "<tr><td>" + data.second_fee_list[i].fee_type + "</td>";
                        tableString += "<td>" + data.second_fee_list[i].fee_amount + "</td>";
                        tableString += "<td>" + data.second_fee_list[i].fee_paid + "</td>";
                        tableString += "<td>" + data.second_fee_list[i].fee_left + "</td>";
                        if(data.second_fee_list[i].fee_left>0){
                            tableString += "<td><input type='text' id='amount"+data.second_fee_list[i].fee_id+"'></td>";
                            tableString += "<td><a type='button' class='btn btn-info savepay' onclick='pay_amount("+data.second_fee_list[i].fee_id+")'>Submit</a></td></tr>";
                        } else {
                            tableString += "<td></td>";
                            tableString += "<td></tr>";
                        }
                    }
                }
                $("#tbody2").html(tableString);
                tableString = "";
                if(data.third_fee_list.length === 0) {
                    tableString = "<tr><td></td><td></td><td>No fee available.</td><td></td><td></td></tr>";
                }
                else {
                    for(var i in data.third_fee_list){
                        tableString += "<tr><td>" + data.third_fee_list[i].fee_type + "</td>";
                        tableString += "<td>" + data.third_fee_list[i].fee_amount + "</td>";
                        tableString += "<td>" + data.third_fee_list[i].fee_paid + "</td>";
                        tableString += "<td>" + data.third_fee_list[i].fee_left + "</td>";
                        if(data.third_fee_list[i].fee_left>0){
                            tableString += "<td><input type='text' id='amount"+data.third_fee_list[i].fee_id+"'></td>";
                            tableString += "<td><a type='button' class='btn btn-info' onclick='pay_amount("+data.third_fee_list[i].fee_id+")'>Submit</a></td></tr>";
                        } else {
                            tableString += "<td></td>";
                            tableString += "<td></tr>";
                        }
                    }
                }
                $("#tbody3").html(tableString);
             }
        });
    });
    function pay_amount(id){
        
        
        var text_id = "#amount" + id;
        var pay_value = $(text_id).val();
        $.ajax({
            type:'POST',
            url:'/pay_by_id/',
            data:{
            'pay_id': id,
            'pay_amount': pay_value,
            },
            success:function(data){
                $("#enr_submit").click();
            },
        });
    }
    function getCookie(c_name) {
        if (document.cookie.length > 0)
        {
            c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1)
            {
                c_start = c_start + c_name.length + 1;
                c_end = document.cookie.indexOf(";", c_start);
                if (c_end == -1) c_end = document.cookie.length;
                return unescape(document.cookie.substring(c_start,c_end));
            }
        }
        return "";
    }
    $(function(){
        $.ajaxSetup({
            headers:{"X-CSRFToken":getCookie('csrftoken')}
        });
    });
</script>
{% endblock content %}

feeplan/templates/feeplan/feeplan_create.html
{% extends 'student/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-xs-10 col-sm-offset-3">
                <form action="" class="frmbgg clear-fx"  method="POST" id="mysectionForm" data-course-url="{% url 'ajax_load_course' %}" data-batch-url="{% url 'ajax_load_batch' %}" data-fee-url="{% url 'ajax_load_feeplan' %}" data-view-list-url="{% url 'ajax_load_list_data' %}">
                    <div class="row">
                        {% csrf_token %}
                        <div class="form-group col-sm-3 col-xs-12">
                            <label>Stream</label>
                            {{ form.stream}}
                        </div>
                        <div class="form-group col-sm-3 col-xs-12">
                            <label>Course</label>
                            {{ form.course}}
                        </div>
                        <div class="form-group col-sm-3 col-xs-12">
                            <label>Batch</label>
                            {{ form.batch}}
                        </div>
                        <div class="form-group col-sm-3 col-xs-12">
                            <label>Fees Type</label>
                            {{ form.fees_type}}
                        </div>
                        <div class="form-group col-sm-3 col-xs-12">
                            <label>Year</label>
                            {{ form.year}}
                        </div>
                        <div class="form-group col-sm-3 col-xs-12">
                            <label>Actual Fees</label>
                            {{ form.actual_fees}}
                        </div>
                        <div class="form-group col-sm-3 col-xs-12">
                            <label>Default Installment</label>
                            {{ form.default_installment}}
                        </div>
                        
                        
                    </div>
                    <button type="submit" class="btn btn-info subbtn" id="submit_attn">Submit</button>
                    <input type="hidden" name="student_section" id="total_count" hidden="hidden" value="">
                    
                </form>
                
            </div>
            <div class="col-xs-10 col-sm-8 col-sm-offset-3">
                <table class="table table-bordered table-striped table-condensed" id="feeplan_create_list">
                    <thead>
                        <tr class="hdclr">
                            <th>Sl No</th>                                
                            <th>Name</th>                                
                            <th>Amount</th>
                        </tr>
                    </thead>
                    <tbody id="fee_create">   
                        {% for stud in objects %}     
                        <tr>                                                           
                            <td>{{stud.id}}</td> 
                            <td>{{stud.fees_type}}</td>              
                            <td>{{stud.actual_fees}}</td>
                        </tr>  
                        {% endfor %}   
                        
                    </tbody>
                </table>  
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript">
$("#id_stream").change(function(event){
            console.log("Hello");
            event.preventDefault();
            var url=$("#mysectionForm").attr("data-course-url");
            var stream_id=$(this).val();
            $.ajax({
                url:url,
            data:{
                'stream':stream_id,
            },
            success:function(data){
                $("#id_course").html(data);
            }
            });

        });
    $("#id_course").change(function(event){
        event.preventDefault();
        var url=$("#mysectionForm").attr("data-batch-url");
        var course_id=$(this).val();
        $.ajax({
            url:url,
        data:{
            'course':course_id,
        },
        success:function(data){
            $("#id_batch").html(data);
        }
        });
    });

    $("#id_batch").change(function(event){
        event.preventDefault();
        var url=$("#mysectionForm").attr("data-fee-url");
        console.log(url);
        var stream_id=$("#id_stream").val();
        var course_id=$("#id_course").val();
        var batch_id=$("#id_batch").val();
        console.log();
        var current_url=$(location).attr('href');
    $.ajax({
        url:url,
        data:{
        'course_id':course_id,
        'stream_id':stream_id,
        'batch_id':batch_id,
        },
        success:function(data){
                $("#id_fees_type").html(data);
             }
        });
    });
    $("#submit_attn").on('click', function(){
        event.preventDefault();
        var url=$("#mysectionForm").attr("data-fee-url");
        console.log(url);
        var stream_id=$("#id_stream").val();
        var course_id=$("#id_course").val();
        var batch_id=$("#id_batch").val();
        var fees_type_id=$("#id_fees_type").val();
        var year_id=$("#id_year").val();
        var actual_fees_id=$("#id_actual_fees").val();
        var default_installment_id=$("#id_default_installment").val();
        
        console.log();
        var current_url=$(location).attr('href');

        $.ajax({
        url:'/ajax_load_list_data_fee/',
        data:{
        'course_id':course_id,
        'stream_id':stream_id,
        'batch_id':batch_id,
        'fees_type_id':fees_type_id,
        'year_id':year_id,
        'actual_fees_id':actual_fees_id,
        'default_installment_id':default_installment_id,
        },
        success:function(data){
                $("#fee_create").html(data);
             }
        });
    });
</script>
{% endblock content %}

feeplan/templates/feeplan/feeplan_create_list.html
{% for stud in objects %}     
<tr>                                                           
    <td>{{stud.id}}</td> 
    <td>{{stud.fees_type}}</td>              
    <td>{{stud.actual_fees}}</td>
</tr>  
{% endfor %}       

feeplan/templates/feeplan/feeplan_list.html
{% extends 'student/base.html' %}
{% block content %}
<section id="main-content">
        <div class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel">
                        <header class="panel-heading clearfix col-sm-12">                            
                            <form class="form-horizontal" role="form" id="assignSubjectTeacherForm" data-course-url="{% url 'ajax_load_course' %}" data-batch-url="{% url 'ajax_load_batch' %}">
                            <div class="col-sm-3 col-xs-12">
                                <div class="input-group" style="width: 100%;">
                                        <select class="form-control" id="id_stream">
                                            {% for obj in stream_object %}
                                            <option value="{{obj.pk}}" selected=""> {{obj.name}}</option>                                           
                                            {% endfor %}
                                        </select>                           
                                    
                                </div>
                            </div>
                            <div class="col-sm-3 col-xs-12">
                                <div class="input-group" style="width: 100%;">
                                  
                                        <select class="form-control" id="id_course">
                                                {% for obj in course_object %}
                                                <option value="{{obj.pk}}" selected=""> {{obj.course_name}}</option>                                           
                                                {% endfor %}
                                        </select>
                                    </div>
                            </div>
                            <div class="col-sm-3 col-xs-12">
                                <div class="input-group" style="width: 100%;">
                                    
                                        <select class="form-control" id="id_batch">
                                                {% for obj in batch_obj %}
                                                <option value="{{obj.pk}}" selected=""> {{obj.batch_no}}</option>                                           
                                                {% endfor %}
                                        </select>                                  
                                    
                                </div>
                            </div>
                            <div class="col-sm-1 col-xs-12 col-sm-offset-2">
                                <button type="button" value="View" class="vwe" data-toggle="collapse" id="listview" data-target="#demo" data-view-list-url="{% url 'ajax_load_list_data' %}">View</button>
                            </div>
                        </form>
                        </header>
                        <div class="panel-body collapse" style="overflow-x:auto;" id="demo">                        
                        </div>                     
                    </div>
                </div>
            </div>
        </div>
    </section>
<script type="text/javascript">
    $("#listview").on('click', function(event){
        //event.preventDefault();
        var url=$("#listview").attr("data-view-list-url");
        var stream_id=$("#id_stream").val();
        var batch_id=$("#id_batch").val();
        var course_id=$("#id_course").val();
    $.ajax({
        url:url,
        data:{
        'batch_id':batch_id,
        'stream_id': stream_id,
        'course_id': course_id,
        },
        success:function(data){
                $("#demo").html(data);
             }
        });
    });
</script>

<script type="text/javascript">
    $("#id_stream").change(function(){
        var url=$("#assignSubjectTeacherForm").attr("data-course-url");
        var stream_id=$(this).val();
        $.ajax({
            url:url,
        data:{
            'stream':stream_id,
        },
        success:function(data){
            $("#id_course").html(data);
        }
        });
    });
    $("#id_course").change(function(){
        var url=$("#assignSubjectTeacherForm").attr("data-batch-url");
        var course_id=$(this).val();
        $.ajax({
            url:url,
            data:{
                'course':course_id,
            },
            success:function(data){
                $("#id_batch").html(data);
            }
        });
    });
    $("#id_batch").change(function(){
        var url=$("#assignSubjectTeacherForm").attr("data-semestar-url");
        var batch_id=$(this).val();
        var course_id=$("#id_course").val();
        var stream_id = $("#id_stream").val();
        $.ajax({
            url:url,
            data:{
                'batch_id': batch_id,
                'course':course_id,
                'stream_id': stream_id,
            },
            success:function(data){
                $("#id_semestar").html(data);
            }
        });
    });
    
</script>
{% endblock content %}