college_erp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student.urls')),
    #path('',include('course.urls')),
    path('',include('coursemanagement.urls')),
    path('',include('feeplan.urls')),
    path('',include('employee.urls')),
    path('',include('user.urls')),
    path('',include('academics.urls')),  
    path('',include('exam.urls')),
    path('',include('collegesetup.urls')),
    path('',include('library.urls')),
    path('',include('hostel.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

coursemanagement/urls.py
from django.urls import path
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns=[
    path('stream_create/',views.StreamCreateView.as_view(),name='stream_create'),
    path('stream_list/',login_required(views.StreamListView.as_view(),login_url='/login'), name='stream_list'),
    path('coursemanagement/course_create/',views.CourseCreateView.as_view(),name='course_create'),
    path('coursemanagement/batch_create/',views.BatchCreateView.as_view(),name='batch_create'),
    path('coursemanagement/section_create/',views.SectionCreateView.as_view(),name='section_create'),
    path('coursemanagement/course_edit/<int:pk>/',login_required(views.CourseUpdateView.as_view(),login_url='/login'), name='course_edit'),
    path('coursemanagement/batch_edit/<int:pk>/',login_required(views.BatchUpdateView.as_view(),login_url='/login'), name='batch_update'),
    path('coursemanagement/section_edit/<int:pk>/',login_required(views.SectionUpdateView.as_view(),login_url='/login'), name='section_edit'), 
    path('coursemanagement/course_list/',login_required(views.CourseListView.as_view(),login_url='/login'), name='course_list'),
    path('coursemanagement/batch_list/',login_required(views.BatchListView.as_view(),login_url='/login'), name='batch_list'),
    path('coursemanagement/section_list/',login_required(views.SectionListView.as_view(),login_url='/login'), name='section_list'),
    path('coursemanagement/course_detail/<int:pk>/',login_required(views.CourseDetailView.as_view(),login_url='/login'),name='course_detail'),
    path('coursemanagement/batch_detail/<int:pk>/',login_required(views.BatchDetailView.as_view(),login_url='/login'),name='batch_detail'),
    path('coursemanagement/section_detail/<int:pk>/',login_required(views.SectionDetailView.as_view(),login_url='/login'),name='section_detail'),
    path('coursemanagement/course_delete/<int:pk>/',login_required(views.CourseDeleteView.as_view(),login_url='/login'),name='course_delete'),
    path('coursemanagement/batch_delete/<int:pk>/',login_required(views.BatchDeleteView.as_view(),login_url='/login'),name='batch_delete'),
    path('coursemanagement/section_delete/<int:pk>/',login_required(views.SectionDeleteView.as_view(),login_url='/login'),name='section_delete'),
    path('ajax_load_course/',views.load_course,name='ajax_load_course'),
    path('ajax_load_batch/',views.load_batch,name='ajax_load_batch'),
    path('ajax_load_section/',views.load_section,name='ajax_load_section'),
    path('ajax_load_feeplan/', views.load_fee_selection, name='ajax_load_feeplan'),
    path('fees_type_create/', views.FeesTypeCreate.as_view(), name="feestype_create"),
    path('feestype_list/', views.FeesTypeList.as_view(), name="feestype_list"),
]

exam/urls.py
from django.urls import path
from . import views


urlpatterns=[
    path('examtype_create/',views.ExamTypeCreate.as_view(), name='exam_type_create'),
    path('examtype_list/',views.exam_list_view, name='exam_type_list'),
    path('examtype_detail/<int:pk>/',views.ExamTypeDetailView.as_view(), name='examtype_detail'),
    path('examtype_update/<int:pk>/',views.ExamTypeUpdateView.as_view(), name='examtype_update'),
    path('examtype_delete/<int:pk>/',views.ExamTypeDeleteView.as_view(), name='examtype_delete'),
    path('course_exam_setting/',views.course_exam_setting, name='course_exam_setting'),
    path('course_exam_setting_ajax/',views.course_exam_setting_ajax, name='course_exam_setting_ajax'),
    path('save_course_exam/',views.save_course_exam, name='save_course_exam'),
    path('subjectexamlist/',views.subjectexamlist, name='subjectexamlist'),
    path('subject_exam_create/',views.SubjectExamCreate.as_view(), name='subject_exam_create'),
    path('subject_exam_update/<int:pk>/',views.SubjectExamPlanUpdate.as_view(), name='subject_exam_update'),
    path('subject_exam_delete/<int:pk>/',views.SubjectExamPlanDelete.as_view(), name='subject_exam_delete'),
    path('exam_attendance/',views.ExamAttendanceCreate.as_view(), name='exam_attendance'),
    path('load_subject_exam/',views.load_subject_exam, name='load_subject_exam'),
    path('examattendancecreate/',views.examattendancecreate, name='examattendancecreate'),
    path('save_exam_attendance/',views.save_exam_attendance, name='save_exam_attendance'),
    path('mark_entry/',views.mark_entry, name='mark_entry'), 
    path('load_date_on_subject_load/',views.load_date_on_subject_load, name='load_date_on_subject_load'),
    path('save_mark_entry/',views.save_mark_entry, name='save_mark_entry'),
    path('mark_entry_ajax/',views.mark_entry_ajax, name='mark_entry_ajax'),    
]

coursemanagement/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.db.models import Sum
from django.core.validators import MaxValueValidator

class MaxLengthIntegerValidator(MaxValueValidator):
    def __init__(self, length):
        max_value = 2**length-5
        super(MaxLengthIntegerValidator, self).__init__(max_value)

class Feestype(models.Model):
    fee_type=models.CharField(max_length=20,unique=True)  
    def __str__(self):
        return "{0}".format(self.fee_type)


class Stream(models.Model):
    name=models.CharField(max_length=50)
    short_name = models.CharField(max_length=4)

    def __str__(self):
        return self.name
class Course(models.Model):
    Exam_choices=(
        ('sem','SEMESTER'),
        ('yr','YEARLY'),
        ('tr','TRIMESTER')
    )
    duration_choice=(
        ('1','1'),
        ('2','2'),
        ('3','3'),
        ('4','4'),
        ('5','5'),
        ('6','6'),
        ('7','7'),
        ('8','8'),
    )
    stream=models.ForeignKey(Stream,on_delete=models.CASCADE)
    course_code=models.CharField(max_length=15)
    course_name=models.CharField(max_length=50)
    course_aliases=models.CharField(max_length=30)
    duration=models.CharField(max_length=1,choices=duration_choice,default='4')
    total_seats=models.IntegerField()
    approved_date=models.DateField()
    exam_pattern=models.CharField(max_length=3,choices=Exam_choices,default='SEMESTER')
    affiliated_body=models.CharField(max_length=30)
    syllabus=models.FileField(blank=False)
    remark=models.TextField()
    #fees=models.ManyToManyField(FeesManagement)

    def __str__(self):
        return self.course_name
class Batch(models.Model):
    stream=models.ForeignKey(Stream,on_delete=models.CASCADE)
    course_name=models.ForeignKey(Course,on_delete=models.CASCADE)
    batch_no=models.CharField(max_length=50)
    starting_date=models.DateField()
    ending_date=models.DateField()
    remark=models.TextField()

    def __str__(self):
        return self.batch_no


    
class FeesManagementSetting(models.Model):
    stream=models.ForeignKey(Stream,on_delete=models.CASCADE)
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    batch=models.ForeignKey(Batch,on_delete=models.CASCADE)
    fees=models.ManyToManyField(Feestype)

    # def total_fees(self):
    #     return sum(self.fees.actual_amount)

    def __str__(self):
        return '{0}-{1}'.format(self.course,self.batch)

coursemanagement/forms.py
from django import forms

from .models import Stream,Batch,Course,Feestype,FeesManagementSetting
from academics.models import Section, Semestar

class StreamForm(forms.ModelForm):
    #DOB = forms.DateField(widget=forms.SelectDateWidget(years=[i for i in range(1920,2010)]),input_formats=['%Y-%m-%d','%m/%d/%Y','%m/%d/%y','%d/%m/%y'])
    class Meta:
        model=Stream
        fields=('__all__')

class CourseForm(forms.ModelForm):
    approved_date = forms.DateField(widget=forms.SelectDateWidget(years=[i for i in range(1920,2010)]),input_formats=['%Y-%m-%d','%m/%d/%Y','%m/%d/%y','%d/%m/%y'])
    class Meta:
        model=Course
        fields=('__all__')

class BatchForm(forms.ModelForm):
    starting_date = forms.DateField(widget=forms.SelectDateWidget(years=[i for i in range(1920,2030)]),input_formats=['%Y-%m-%d','%m/%d/%Y','%m/%d/%y','%d/%m/%y'])
    ending_date = forms.DateField(widget=forms.SelectDateWidget(years=[i for i in range(1920,2030)]),input_formats=['%Y-%m-%d','%m/%d/%Y','%m/%d/%y','%d/%m/%y'])
    class Meta:
        model=Batch
        fields=('__all__')
class SectionForm(forms.ModelForm):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])    
    
    class Meta:
        model=Section
        fields=('__all__')
class FeesForm(forms.ModelForm):
    class Meta:
        model=Feestype
        fields=('__all__')
class FeesManagementSettingForm(forms.ModelForm):
    class Meta:
        model=FeesManagementSetting       
        widgets = {'fees': forms.widgets.CheckboxSelectMultiple() } 
        fields=('__all__')
    # def __init__(self, *args, **kwargs):
    #     super(FeesManagementSettingForm, self).__init__(*args, **kwargs)
    #     self.fields['fees'].widget = forms.CheckboxSelectMultiple

class FeetypeCreateForm(forms.ModelForm):
    class Meta:
        model = Feestype
        fields = ('__all__')

exam/forms.py
from django import forms
from .models import ExamSetting, ExamType, ExamAttendance, SubjectExam
from coursemanagement.models import Stream, Course, Batch
from academics.models import Semestar, Subject

class ExamTypeForm(forms.Form):
    exam_type = forms.CharField(max_length=250)   
          
    def save(self):
        data = self.cleaned_data
        user = ExamType(exam_type=data['exam_type'])
        user.save()

class CourseExamSetting(forms.ModelForm):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])
    semestar = forms.ChoiceField(choices=[(o.id, str(o)) for o in Semestar.objects.all()])
    
    class Meta:
        model = ExamSetting
        fields = ['exam','no_of_exams']

class SubjectExamForm(forms.ModelForm):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])
    semestar = forms.ChoiceField(choices=[(o.id, str(o)) for o in Semestar.objects.all()])   
    
    class Meta:
        model = SubjectExam
        fields = ['subject','exam','full_mark','exam_number']

class ExamAttendanceForm(forms.ModelForm):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])
    semestar = forms.ChoiceField(choices=[(o.id, str(o)) for o in Semestar.objects.all()])
    subject = forms.ChoiceField(choices=[(o.id, str(o)) for o in Subject.objects.all()])
    
    class Meta:
        model = ExamAttendance
        fields = ['attendance_status','exam','enrollment_number','date','marks','remarks']
        
class MarkentryForm(forms.Form):
    stream = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Stream.objects.all()])
    course = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Course.objects.all()])
    batch = forms.ChoiceField(choices=[ (o.id, str(o)) for o in Batch.objects.all()])
    semestar = forms.ChoiceField(choices=[(o.id, str(o)) for o in Semestar.objects.all()])
    subject = forms.ChoiceField(choices=[(o.id, str(o)) for o in Subject.objects.all()])
    date = forms.ChoiceField(choices=[(o.date, str(o.date)) for o in ExamAttendance.objects.all()])
    exam = forms.ChoiceField(choices=[(o.id, str(o)) for o in SubjectExam.objects.all()])
    def save(self):
        data = self.cleaned_data
        user = ExamAttendance(marks=data['marks'])
        user.save()

coursemanagement/templates/coursemanagement/batch_confirm_delete.html
{% comment %} {% extends 'student/base.html' %}
{% load crispy_forms_tags %}
{% block content %}{% endcomment %}
<style>
        .deletebaackgroundbg{
             background-color: #1fb400;
             height: auto;
             width: 600px;
             color: #fff;
             text-align: center;
             margin: 0 auto;
             margin-top: 10%;
             font-size: 28px;
             line-height: 84px;
             padding: 20px 40px 20px 40px;
             border-radius: 20px;
         }
         .deletebaackgroundbg .btmnhk{
             background-color: #141414;
             padding: 12px 60px;
             border: 0;
             outline: 0;
             margin-top: 20px;
             font-size: 16px;
             color: #fff;
             border-radius: 4px;
         }
         .deletebaackgroundbg .btmnhk:hover{
             background-color: #fff;
             color: #141414;
             cursor: pointer;
         }
    </style>
<section> 
   <div class="deletebaackgroundbg">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            Are you sure you want to delete "{{ object }}" ?
            <input type="submit" value="Submit" class="btmnhk" />
        </form>
    </div>
</section>

{% comment %}  {% endblock content %}{% endcomment %}

coursemanagement/templates/coursemanagement/batch_edit.html
{% extends 'student/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<section id="main-content">
    <div class="wrapper">
        <div class="row">
            <div class="col-lg-6 col-sm-6 col-sm-offset-3">
                <div class="">
                    <div class="panel-body">
                        <div class="text-center">
                            <h1 class="hdrcolorbg">
                                Batch
                            </h1>
                        </div>
                        <form role="form" class="frmbgg" action="#" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="row">
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Stream</label>
                                            {{ form.stream }}
                                        </div>
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Course Name</label>
                                            {{ form.course_name }}
                                        </div>
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Batch No.</label>
                                            {{ form.batch_no }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Starting Date</label>
                                            {{ form.starting_date }}
                                        </div>
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Ending Date</label>
                                            {{ form.ending_date }}
                                        </div>
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Remark</label>
                                            {{ form.remark }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-info cancel">Cancel</button>
                            <button type="submit" class="btn btn-info save">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

coursemanagement/templates/coursemanagement/batch_form.html
{% extends 'student/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<script>
        document.getElementById("strm").className += " active";
        document.getElementById("strm1").className += " active";
        document.getElementById("strm03").className += " active";        
</script>
<style>
        #strm03 a{
                color:#fff !important;
        }
</style>
<section id="main-content">
    <div class="wrapper">
        <div class="row">
            <div class="col-lg-6 col-sm-6 col-sm-offset-3">
                <div class="">
                    <div class="panel-body">
                        <div class="text-center">
                            <h1 class="hdrcolorbg">
                                Batch
                            </h1>
                        </div>
                        <form role="form" class="frmbgg" action="#" id="mybatchForm" method="POST" data-course-url="{% url 'ajax_load_course' %}" data-batch-url="{% url 'ajax_load_batch' %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="row">
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Stream</label>
                                            {{ form.stream }}
                                        </div>
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Course Name</label>
                                            {{ form.course_name }}
                                        </div>
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Batch No.</label>
                                            {{ form.batch_no }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-sm-5 col-xs-12 startdt">
                                            <div>
                                                <label>Starting Date</label>
                                            </div>
                                            {{ form.starting_date }}
                                        </div>
                                        <div class="form-group col-sm-5 col-xs-12 enddt">
                                            <div>
                                                <label>Ending Date</label>
                                            </div>
                                            {{ form.ending_date }}
                                        </div>
                                        <div class="form-group col-sm-2 col-xs-12">
                                            <label>Remark</label>
                                            {{ form.remark }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="reset" class="btn btn-info cancel">Cancel</button>
                            <button type="submit" class="btn btn-info save">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript">
$("#id_stream").change(function(event){
            event.preventDefault();
            var url=$("#mybatchForm").attr("data-course-url");
            var stream_id=$(this).val();
            $.ajax({
                url:url,
            data:{
                'stream':stream_id,
            },
            success:function(data){
                $("#id_course_name").html(data);
            }
            });

        });
        $("#id_course_name").change(function(event){
            event.preventDefault();
            var url=$("#mybatchForm").attr("data-batch-url");
            var course_id=$(this).val();
            $.ajax({
                url:url,
            data:{
                'course':course_id,
            },
            success:function(data){
                $("#id_batch_no").html(data);
            }
            });

        });
</script>
{% endblock content %}

coursemanagement/templates/coursemanagement/feesmanagement_detail.html
<table>
    <tr>
        <td>
            Course Name
        </td>
       <td>
            {{object.course}}
       </td>
    </tr>
    <tr>
            <td>
                Batch Name
            </td>
           <td>
                {{object.batch}}
               
           </td>
        </tr>
    <tr>
        <td>
            Fees Type
        </td>
        {% for i in object.fees.all %}
        <td>
                {{i}}
        </td>
        {% endfor %}

    </tr>
</table>

coursemanagement/templates/coursemanagement/feesmanagment_create.html
{% extends 'student/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<script>
        document.getElementById("fee").className += " active";
        document.getElementById("fee1").className += " active";
        document.getElementById("fee02").className += " active";        
</script>
<style>
        #fee02 a{
                color:#fff !important;
        }
</style>
<section id="main-content">
    <div class="wrapper">
        <div class="row">
            <div class="col-lg-4 col-sm-4 col-sm-offset-4">
                <div class="">
                    <div class="panel-body">
                        <div class="text-center">
                            <h1 class="hdrcolorbg">
                                Fees Management
                            </h1>
                        </div>
                        <form role="form" class="frmbgg"  method="post" id="myForm"   data-batch-url="{% url 'ajax_load_batch' %}" >
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="row">
                                        <div class="form-group col-sm-12 col-xs-12">
                                            <label>Course Name</label>
                                            {{form.course}}
                                        </div>
                                        <div class="form-group col-sm-12 col-xs-12">
                                                <label>Batch Name</label>
                                            {{form.batch}}
                                        </div>
                                        <div class="form-group col-sm-12 col-xs-12">
                                                <label>Fees Type</label>
                                                {% for checkbox in form.fees %}
                                                <label>
                                                {{ checkbox.tag }} {{ checkbox.choice_label }}
                                            </label>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-info save">Add</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript">

$("#id_course").change(function(event){
    event.preventDefault();
    var url=$("#myForm").attr("data-batch-url");
    var course_id=$(this).val();
    $.ajax({
        url:url,
        data:{
            'course':course_id,
        },
        success:function(data){
            $("#id_batch").html(data);
        }
    });

});
</script>
{% endblock content %}

coursemanagement/templates/coursemanagement/section_form.html
{% extends 'student/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<script>
        document.getElementById("strm").className += " active";
        document.getElementById("strm1").className += " active";
        document.getElementById("strm04").className += " active";        
</script>
<style>
        #strm04 a{
                color:#fff !important;
        }
</style>
<section id="main-content">
    <div class="wrapper">
        <div class="row">
            <div class="col-lg-6 col-sm-6 col-sm-offset-3">
                <div class="">
                    <div class="panel-body">
                        <div class="text-center">
                            <h1 class="hdrcolorbg">
                                Section
                            </h1>
                        </div>
                        <form role="form" class="frmbgg" action="#" method="POST" id="mysectionForm"  data-course-url="{% url 'ajax_load_course' %}" data-batch-url="{% url 'ajax_load_batch' %}" data-semestar-url="{% url 'ajax_load_sem' %}" data-section-url="{% url 'ajax_load_section' %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="row">
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Stream Name</label>
                                            {{ form.stream }}
                                        </div>
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Course Name</label>
                                            {{ form.course }}
                                        </div>
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Batch No.</label>
                                            {{ form.batch }}
                                        </div>
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Semester</label>
                                            {{ form.semestar }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Section Name</label>
                                            {{ form.section_name }}
                                        </div>
                                        <div class="form-group col-sm-4 col-xs-12">
                                            <label>Remark</label>
                                            {{ form.remark }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="reset" class="btn btn-info cancel">Cancel</button>
                            <button type="submit" class="btn btn-info save">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript">
$("#id_stream").change(function(event){
            event.preventDefault();
            // var url=$("#mysectionForm").attr("data-course-url");
            var stream_id=$(this).val();
            $.ajax({
                url:'/ajax_load_course/',
            data:{
                'stream':stream_id,
            },
            success:function(data){
                $("#id_course").html(data);
            }
            });

        });
    $("#id_course").change(function(event){
        event.preventDefault();
        var url=$("#mysectionForm").attr("data-batch-url");
        var course_id=$(this).val();
        $.ajax({
            url:'/ajax_load_batch/',
        data:{
            'course':course_id,
        },
        success:function(data){
            $("#id_batch").html(data);
        }
        });

    });
    $("#id_batch").change(function(event){
        var batch_id=$(this).val();
        course=$("#id_course").val();
        stream_id=$("#id_stream").val();
        $.ajax({
            url:'/ajax_load_sem/',
            data:{
            'batch_id':batch_id,
            'course':course,
            'stream_id':stream_id,
            },
            success:function(data){
                    $("#id_semestar").html(data);
                }
            });
        });
    // $("#id_semestar").change(function(){
    //     var url=$("#lessonPlan").attr("data-subject-url");
    //     var semestar_id =$(this).val();
    //     $.ajax({
    //         url:'/ajax_load_sem/',
    //         data:{
    //             'semestar_id': semestar_id,
    //         },
    //         success:function(data){
    //             $("#id_section_name").html(data);
    //         }
    //     });
    // });

</script>
{% endblock content %}